=== ewanv/pudding/WebContent/WEB-INF/articles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uts.edu.au/31284/wsd-diary" xmlns="http://www.uts.edu.au/31284/wsd-diary"
	elementFormDefault="qualified">

	<!-- Schema definition for Articles. In-built data types used for precision. 
		Articles have an ID, title, published date, author ID, full text, category 
		tag and an "Author only" flag. -->

	<!-- Type Declarations -->
		<xs:simpleType name="category">
			<xs:restriction base="xs:string">
				<xs:enumeration value="News" />
				<xs:enumeration value="Sport" />
				<xs:enumeration value="Entertainment" />
				<xs:enumeration value="Business" />
				<xs:enumeration value="Technology" />
			</xs:restriction>
		</xs:simpleType>
		
		<xs:simpleType name="id">
			<xs:restriction base="xs:long">
				<xs:minInclusive value="1" />
			</xs:restriction>
		</xs:simpleType>

	<!-- Element Declarations -->

	<xs:element name="articles">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="article" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:long" />
							<xs:element name="title" type="xs:string" />
							<xs:element name="publishedDate" type="xs:date" />
							<xs:element name="authorId" type="xs:long" />
							<xs:element name="fullText" type="xs:string" />
							<xs:element name="categoryTag" type="category" />
							<xs:element name="authorOnly" type="xs:boolean" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ewanv/pudding/WebContent/WEB-INF/articles.xml
<?xml version="1.0" encoding="UTF-8"?>
<articles xmlns="http://www.uts.edu.au/31284/wsd-diary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary articles.xsd">

	<article>
		<id>0</id>
		<title>Blah blah blah</title>
		<publishedDate>01/01/2014</publishedDate>
		<authorId>0</authorId>
		<fullText>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae
			dignissim ante, vel facilisis urna. Donec sit amet neque blandit,
			laoreet ipsum sit amet, imperdiet dui. Vivamus suscipit, odio in
			lacinia adipiscing, ante ante viverra quam, vitae consequat mauris
			dui semper nulla. Etiam aliquet arcu mauris, id egestas urna
			sollicitudin vitae. Ut id laoreet augue. Nam congue accumsan nunc, in
			blandit velit pretium vitae. Donec nulla odio, vulputate at massa
			vitae, lacinia viverra libero. Sed hendrerit semper iaculis. Mauris
			sed tortor sem. Nulla pharetra sed sem eu posuere. Praesent
			pellentesque, est at semper mollis, justo tellus pulvinar augue, in
			pretium dolor libero at erat. Duis at eleifend sem, vel mattis nulla.

			Nulla id nibh laoreet, ultrices dui quis, luctus lorem. Praesent eget
			tincidunt lacus. Donec sapien purus, pellentesque sed arcu nec,
			volutpat imperdiet lorem. Sed consequat ante eget nisl varius, id
			dignissim ante scelerisque. Mauris pretium, mi non laoreet euismod,
			tortor lorem fringilla magna, a lacinia lacus arcu at felis.
			Curabitur sed tempor tortor, eget mollis quam. Sed dignissim odio sed
			tellus venenatis pretium. Phasellus pharetra ligula eget nibh luctus,
			vitae blandit nibh consequat.
		</fullText>
		<categoryTag>entertainment</categoryTag>
	</article>
	<article>
		<id>0</id>
		<title>Foo Bar</title>
		<publishedDate>01/01/2014</publishedDate>
		<authorId>0</authorId>
		<fullText>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae
			dignissim ante, vel facilisis urna. Donec sit amet neque blandit,
			laoreet ipsum sit amet, imperdiet dui. Vivamus suscipit, odio in
			lacinia adipiscing, ante ante viverra quam, vitae consequat mauris
			dui semper nulla. Etiam aliquet arcu mauris, id egestas urna
			sollicitudin vitae. Ut id laoreet augue. Nam congue accumsan nunc, in
			blandit velit pretium vitae. Donec nulla odio, vulputate at massa
			vitae, lacinia viverra libero. Sed hendrerit semper iaculis. Mauris
			sed tortor sem. Nulla pharetra sed sem eu posuere. Praesent
			pellentesque, est at semper mollis, justo tellus pulvinar augue, in
			pretium dolor libero at erat. Duis at eleifend sem, vel mattis nulla.

			Nulla id nibh laoreet, ultrices dui quis, luctus lorem. Praesent eget
			tincidunt lacus. Donec sapien purus, pellentesque sed arcu nec,
			volutpat imperdiet lorem. Sed consequat ante eget nisl varius, id
			dignissim ante scelerisque. Mauris pretium, mi non laoreet euismod,
			tortor lorem fringilla magna, a lacinia lacus arcu at felis.
			Curabitur sed tempor tortor, eget mollis quam. Sed dignissim odio sed
			tellus venenatis pretium. Phasellus pharetra ligula eget nibh luctus,
			vitae blandit nibh consequat.
		</fullText>
		<categoryTag>News</categoryTag>
	</article>
	
</articles>
