=== ewanv/pudding/WebContent/WEB-INF/authors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uts.edu.au/31284/wsd-diary" xmlns="http://www.uts.edu.au/31284/wsd-diary"
	elementFormDefault="qualified">

	<!-- Schema definition for Authors. In-built data types used for precision. 
		Authors have an ID, name, date of birth, bio, username and password. -->

	<!-- Type declarations -->
	<xs:simpleType name="id">
		<xs:restriction base="xs:long">
			<xs:minInclusive value="1" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Element declarations -->
	<xs:element name="authors">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="author" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="id" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="dateOfBirth" type="xs:date" />
							<xs:element name="bio" type="xs:string" />
							<xs:element name="username" type="xs:string" />
							<xs:element name="password" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>


			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ewanv/pudding/WebContent/WEB-INF/authors.xml
<?xml version="1.0" encoding="UTF-8"?>
<authors xmlns="http://www.uts.edu.au/31284/wsd-diary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary authors.xsd">

	<author>
		<id>0</id>
		<name>Michael J. Fox</name>
		<dateOfBirth>01/01/1992</dateOfBirth>
		<bio>Michael J. Fox, OC (born Michael Andrew Fox; June 9, 1961) is a
			Canadianâ€“American actor, author, comedian, producer, advocate and
			voice-over artist.</bio>
		<username>foxymike69</username>
		<password>1234</password>
	</author>


</authors>
