=== ewanv/pudding/WebContent/WEB-INF/newsapplication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uts.edu.au/31284/wsd-diary" xmlns="http://www.uts.edu.au/31284/wsd-diary"
	elementFormDefault="qualified">

	<!-- Insert your type declarations here -->
	<xs:simpleType name="date">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,2}/\d{1,2}/\d{4}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Insert your element declarations here -->

	<xs:element name="newsApp">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="articles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="article">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:long" />
										<xs:element name="title" type="xs:string" />
										<xs:element name="publishedDate" type="date" />
										<xs:element name="authorId" type="xs:long" />
										<xs:element name="fullText" type="xs:string" />
										<xs:element name="categoryTag" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="authors">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="author">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:long" />
										<xs:element name="name" type="xs:string" />
										<xs:element name="dateOfBirth" type="date" />
										<xs:element name="bio" type="xs:string" />
										<xs:element name="username" type="xs:string" />
										<xs:element name="password" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>

				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ewanv/pudding/WebContent/WEB-INF/newsapplication.xml
<?xml version="1.0" encoding="UTF-8"?>
<newsApp xmlns="http://www.uts.edu.au/31284/wsd-diary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary newsapplication.xsd">

	<author>
		<id>0</id>
		<hame>Michael J. Fox</hame>
		<dateOfBirth>01/01/1992</dateOfBirth>
		<bio>Michael J. Fox, OC (born Michael Andrew Fox; June 9, 1961) is a
			Canadianâ€“American actor, author, comedian, producer, advocate and
			voice-over artist.</bio>
		<username>foxymike69</username>
		<password>1234</password>
	</author>

	<article>
		<id>0</id>
		<publishedDate>01/01/2014</publishedDate>
		<authorId>0</authorId>
		<fullText>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae
			dignissim ante, vel facilisis urna. Donec sit amet neque blandit,
			laoreet ipsum sit amet, imperdiet dui. Vivamus suscipit, odio in
			lacinia adipiscing, ante ante viverra quam, vitae consequat mauris
			dui semper nulla. Etiam aliquet arcu mauris, id egestas urna
			sollicitudin vitae. Ut id laoreet augue. Nam congue accumsan nunc, in
			blandit velit pretium vitae. Donec nulla odio, vulputate at massa
			vitae, lacinia viverra libero. Sed hendrerit semper iaculis. Mauris
			sed tortor sem. Nulla pharetra sed sem eu posuere. Praesent
			pellentesque, est at semper mollis, justo tellus pulvinar augue, in
			pretium dolor libero at erat. Duis at eleifend sem, vel mattis nulla.

			Nulla id nibh laoreet, ultrices dui quis, luctus lorem. Praesent eget
			tincidunt lacus. Donec sapien purus, pellentesque sed arcu nec,
			volutpat imperdiet lorem. Sed consequat ante eget nisl varius, id
			dignissim ante scelerisque. Mauris pretium, mi non laoreet euismod,
			tortor lorem fringilla magna, a lacinia lacus arcu at felis.
			Curabitur sed tempor tortor, eget mollis quam. Sed dignissim odio sed
			tellus venenatis pretium. Phasellus pharetra ligula eget nibh luctus,
			vitae blandit nibh consequat.
		</fullText>
		<categoryTag>entertainment</categoryTag>
	</article>

</newsApp>
